<?php

	if(!defined('ABSPATH')) exit; //Don't run if accessed directly


	/**
	 *
	 * @package wpblogroll
	 *
	 * create blogroll shortcode
	 *
	*/
	


	function blogroll_shortcode() {
		
		// Get site root and delete OPML file if exists

		$root = $_SERVER['DOCUMENT_ROOT'];
		$file = $root . '/blogroll.opml';

		if ( file_exists( $file ) ) {
		  unlink( $file );
		}

		$opmlfile = fopen($file, 'w');
		fwrite($opmlfile, '<?xml version="1.0" encoding="ISO-8859-1"?>'.PHP_EOL);
		fwrite($opmlfile, "<!-- OPML generated by the Webmention Directory WordPress plugin -->".PHP_EOL);
		fwrite($opmlfile, "<!-- Dynamically created on " . date('d/m/Y') . " -->".PHP_EOL);
		fwrite($opmlfile, '<opml version="2.0">'.PHP_EOL);
		fwrite($opmlfile, "\t<head>".PHP_EOL);
		fwrite($opmlfile, "\t\t<title>Blogroll links for " . get_bloginfo('name') . "</title>".PHP_EOL);
		fwrite($opmlfile, "\t\t<dateModified>" . date('D, d M Y H:i:s') . " GMT</dateModified>".PHP_EOL);
		fwrite($opmlfile, "\t</head>".PHP_EOL);
		fwrite($opmlfile, "\t<body>".PHP_EOL);
		fwrite($opmlfile, "\t\t<outline type='category' title='Bloggers'>".PHP_EOL);
		
		
		// setup query and get entries

		global $wp_query;
		global $post;
		
		$args = array(
        	'order'   => 'ASC',
			'post_type'	=> 'blogroll',
		);
		
		$query = new WP_Query( $args );
		
		if ( $query->have_posts() ) : ?>

		    <?php while ( $query->have_posts() ) : $query->the_post(); 
				$id = $post->ID;
				$name = get_the_title();
				$link = get_post_meta( $id, 'linkurl', true );
				$feed = get_post_meta( $id, 'feedurl', true );
			?>   
				
        		<div class="blogroll-item">
            		<h1 class="blogroll-title"><a href="<?php echo $link; ?>"><?php the_title(); ?></a></h1>
					<?php the_content(); ?>
					<a href="<?php echo $feed; ?>">RSS Feed</a>
        		</div>

				<?php
					fwrite($opmlfile, "\t\t\t<outline text='" . $name . "' xmlUrl='" . $feed . "' htmlUrl='" . $link . "' />".PHP_EOL);
				?>

    		<?php endwhile; wp_reset_postdata(); 
		endif;
		
		fwrite($opmlfile, "\t\t</outline>".PHP_EOL);
		fwrite($opmlfile, "\t</body>".PHP_EOL);
		fwrite($opmlfile, "</opml>".PHP_EOL);
		fclose($opmlfile);
		
		$domain = 'http' . (isset($_SERVER['HTTPS']) ? 's' : '') . '://' . "{$_SERVER['HTTP_HOST']}";
		$opmlpath = $domain . '/blogroll.opml';
		
		?>

		<div class="opmllink">
			Grab the <a href="<?php echo $opmlpath ?>">OPML file</a>
		</div>

<?php
			
	}